name: GSPro Flightscope Connect Bug report
description: Method of reporting GSPro Flightscope Connect Bugs
title: "[Bug]:"
labels: ["bug","gspro"]
assignees: 
  - tnbozman
body:
  - type: markdown
    attributes:
      value: |
        Please complete the following form to log your bug
  - type: dropdown
    id: gspro-connect-only
    attributes:
      label: This bug relates to GSPro Connect only (not the game itself)
      description: GSPro Flightscope connect bugs only confirmation
      options:
        - Yes
        - No (please raise your bug with GSPro support)
    validations:
      required: true
  - type: input
    id: gspro-version
    attributes:
      label: GSPro Version
      description: Version of GSPro you are experiencing the bug
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
      render: shell
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Steps to reproduce bug
      description: Details steps to reproduce the bug
      render: shell
    validations:
      required: false
  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      render: shell
    validations:
      required: true
  - type: textarea
    id: bug-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: bug-additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
      render: shell
